In [1]:
# 라이브러리 불러오기
import pandas as pd  # pandas 모듈을 pd로 지정
from sklearn.model_selection import train_test_split  # sklearn.model_selection 모듈에서 함수 train_test_split 불러오기
from sklearn.preprocessing import StandardScaler  # sklearn.preprocessing 모듈에서 함수 StandardScaler 불러오기
from sklearn.metrics import accuracy_score  # sklearn.metrics 모듈에서 함수 accuracy_score 불러오기
from sklearn.tree import DecisionTreeClassifier # sklearn.tree 모듈에서 함수 DecisionTreeClassifier 불러오기
from sklearn.ensemble import RandomForestClassifier # sklearn.ensemble 모듈에서 함수 RandomForestClassifier 불러오기
from sklearn.svm import SVC # sklearn.svm 모듈에서 함수 SVC 불러오기
from sklearn.linear_model import LogisticRegression # sklearn.linear_model 모듈에서 함수LogisticRegression 불러오기
from sklearn.neighbors import KNeighborsClassifier # sklearn.neighbors 모듈에서 함수 KNeighborsClassifier 불러오기

# 데이터 로드
file_path = "C:/Users/LIM/OneDrive/바탕 화면/study/인공지능개론/mobile.csv"  # 파일 경로 입력
data = pd.read_csv(file_path)  # 입력한 경로에 있는 파일 읽

# 데이터 확인
data.head()  # 올바른 데이터를 로드했는지 확인을 위해 상위 5행 출력

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,...,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_range
0,842,0,2.2,0,1,0,7,0.6,188,2,...,20,756,2549,9,7,19,0,0,1,1
1,1021,1,0.5,1,0,1,53,0.7,136,3,...,905,1988,2631,17,3,7,1,1,0,2
2,563,1,0.5,1,2,1,41,0.9,145,5,...,1263,1716,2603,11,2,9,1,1,0,2
3,615,1,2.5,0,0,0,10,0.8,131,6,...,1216,1786,2769,16,8,11,1,0,0,2
4,1821,1,1.2,0,13,1,44,0.6,141,2,...,1208,1212,1411,8,2,15,1,1,0,1

In [2]:
# X, y 나누기 (X : 입력 데이터, Y : 정답)
X = data.iloc[:, :-1]  # 모든 행과 마지막 열 제외한 것
y = data.iloc[:, -1]   # 모든 행과 마지막 열 선택한 것

In [3]:
X  # mobile.csv에서 마지막 열을 제외한 모든 행이 선택되었는지 확인을 위해 출력

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,pc,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi
0,842,0,2.2,0,1,0,7,0.6,188,2,2,20,756,2549,9,7,19,0,0,1
1,1021,1,0.5,1,0,1,53,0.7,136,3,6,905,1988,2631,17,3,7,1,1,0
2,563,1,0.5,1,2,1,41,0.9,145,5,6,1263,1716,2603,11,2,9,1,1,0
3,615,1,2.5,0,0,0,10,0.8,131,6,9,1216,1786,2769,16,8,11,1,0,0
4,1821,1,1.2,0,13,1,44,0.6,141,2,14,1208,1212,1411,8,2,15,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,794,1,0.5,1,0,1,2,0.8,106,6,14,1222,1890,668,13,4,19,1,1,0
1996,1965,1,2.6,1,0,0,39,0.2,187,4,3,915,1965,2032,11,10,16,1,1,1
1997,1911,0,0.9,1,1,1,36,0.7,108,8,3,868,1632,3057,9,1,5,1,1,0
1998,1512,0,0.9,0,4,1,46,0.1,145,5,5,336,670,869,18,10,19,1,1,1
1999,510,1,2.0,1,5,1,45,0.9,168,6,16,483,754,3919,19,4,2,1,1,1

In [4]:
y  # mobile.csv에서 마지막 열만을 선택한 모든 행이 선택되었는지 확인을 위해 출력

0       1
1       2
2       2
3       2
4       1
       ..
1995    0
1996    2
1997    3
1998    0
1999    3
Name: price_range, Length: 2000, dtype: int64

In [5]:
# 데이터 분할
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)  # 80%로 학습, 20%로 테스트 데이터로 랜덤으로 나눔, random_state가 설정한 이유는 항상 같은 결과를 도출할 수 있어서

In [7]:
# 정규화
scaler = StandardScaler()  # StandardScaler 객체 생성
X_train = scaler.fit_transform(X_train)  # X_train 데이터의 평균과 표준편차를 계산하고 이를 통해 정규화 진행
X_test = scaler.transform(X_test)  # X_train 데이터에서 계산된 평균과 표준편차를 이용해 변환

In [8]:
# Decision Tree
model = DecisionTreeClassifier(random_state=42)  # DecisionTreeClassifier 모델 생성 
model.fit(X_train, y_train)  # X_train 데이터의 패턴으로 모델을 학습
y_pred = model.predict(X_test)  # 학습된 모델로 X_test에 대해 예측

print("Decision Tree Accuracy:", accuracy_score(y_test, y_pred))  # Decision Tree Accuracy 출력

Decision Tree Accuracy: 0.835

In [9]:
# RandomForest
model = RandomForestClassifier(n_estimators=100, random_state=42)  #RandomForestClassifier 모델 생성, 100개의 DT를 사용해 학습 진행
model.fit(X_train, y_train)  # X_train 데이터의 패턴으로 모델을 학습
y_pred = model.predict(X_test)  # 학습된 모델로 X_test에 대해 예측

print("Random Forest Accuracy:", accuracy_score(y_test, y_pred))  # Random Forest Accuracy 출력

Random Forest Accuracy: 0.8925

In [10]:
# SVC
model = SVC(kernel="linear", random_state=42)  # SVC 모델 생성, 선형 커널 사용
model.fit(X_train, y_train)  # X_train 데이터의 패턴으로 모델을 학습
y_pred = model.predict(X_test)  # 학습된 모델로 X_test에 대해 예측

print("SVM Accuracy:", accuracy_score(y_test, y_pred))  # SVM Accuracy 출력

SVM Accuracy: 0.97

In [11]:
# LogisticRegression
model = LogisticRegression(max_iter=200, random_state=42)  # LogisticRegression 모델 생성,  최대 반복 횟수 200 설정
model.fit(X_train, y_train)  # X_train 데이터의 패턴으로 모델을 학습
y_pred = model.predict(X_test)  # 학습된 모델로 X_test에 대해 예측

print("Logistic Regression Accuracy:", accuracy_score(y_test, y_pred))  # Logistic Regression Accuracy 출력

Logistic Regression Accuracy: 0.975

In [12]:
# KNN
knn = KNeighborsClassifier(n_neighbors=3)  # KNN 모델 생성, 예측을 위한 이웃의 수 설정
knn.fit(X_train, y_train)  # X_train 데이터의 패턴으로 Knn을 학습
y_pred = knn.predict(X_test)  # 학습된 모델로 X_test에 대해 예측

print("K-Nearest Neighbors Accuracy:", accuracy_score(y_test, y_pred))  # K-Nearest Neighbors Accuracy 출력

K-Nearest Neighbors Accuracy: 0.4825